# Generated by Django 4.1.7 on 2023-03-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffees_api', '0004_rename_blend_coffee_blend_id'),
        ('locations_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_coffees', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coffee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees_api.coffee')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations_api.location')),
            ],
        ),
    ]
