# Generated by Django 4.1.7 on 2023-03-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0002_alter_sale_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
