# Generated by Django 4.1.7 on 2023-03-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_api', '0001_initial'),
        ('coffees_api', '0004_rename_blend_coffee_blend_id'),
        ('sales_api', '0004_alter_sale_revenue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('coffee_id', 'location_id')},
        ),
    ]
