# Generated by Django 4.1.7 on 2023-04-14 12:58

from django.db import migrations, models
import sales_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0005_alter_sale_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='revenue',
            field=models.FloatField(null=True, validators=[sales_api.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_coffees',
            field=models.IntegerField(validators=[sales_api.models.validate_positive]),
        ),
    ]
