# Generated by Django 4.1.7 on 2023-05-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_api', '0006_alter_sale_revenue_alter_sale_sold_coffees'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
