version: "3.8"

services:
  server:
    build: ./server
    command: gunicorn cafe.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./server/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./server/.env.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email andrei.dragan@stud.ubbcluj.ro --agree-tos --no-eff-email -d eveiller.ignorelist.com
volumes:
  postgres_data:
  certbot:
  nginx:
