version: "3.8"

services:
  server:
    build: ./server
    command: >
      gunicorn cafe.wsgi:application --bind 0.0.0.0:8000
      --timeout 1200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8000
    env_file:
      - ./server/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./server/.env.db
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - PROXY_CONNECT_TIMEOUT=1200s
      - PROXY_SEND_TIMEOUT=1200s
      - PROXY_READ_TIMEOUT=1200s
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - server
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./nginx/.env.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  certs:
  html:
  vhost:
  acme:
