# Generated by Django 4.1.7 on 2023-03-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('in_stock', models.BooleanField()),
            ],
        ),
    ]
