# Generated by Django 4.1.7 on 2023-03-23 18:49

import blends_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blends_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='level',
            field=models.IntegerField(validators=[blends_api.models.validate_blend_level]),
        ),
    ]
