# Generated by Django 4.1.7 on 2023-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blends_api', '0002_alter_blend_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
