# Generated by Django 4.1.7 on 2023-04-14 12:58

import blends_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blends_api', '0004_alter_blend_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='country_of_origin',
            field=models.CharField(max_length=1000, validators=[blends_api.models.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='blend',
            name='description',
            field=models.CharField(max_length=1000, validators=[blends_api.models.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='blend',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[blends_api.models.validate_no_profanity]),
        ),
    ]
