# Generated by Django 4.1.7 on 2023-03-23 18:49

from django.db import migrations, models
import locations_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=50, validators=[locations_api.models.postal_code_length]),
        ),
    ]
