# Generated by Django 4.1.7 on 2023-04-14 12:58

from django.db import migrations, models
import locations_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_api', '0004_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=1000, validators=[locations_api.models.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=1000, validators=[locations_api.models.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(validators=[locations_api.models.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, validators=[locations_api.models.validate_no_profanity]),
        ),
    ]
