# Generated by Django 4.1.7 on 2023-05-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations_api', '0005_alter_location_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
