# Generated by Django 4.1.7 on 2023-03-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blends_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('calories', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('vegan', models.BooleanField()),
                ('blend', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blends_api.blend')),
            ],
        ),
    ]
