# Generated by Django 4.1.7 on 2023-03-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blends_api', '0001_initial'),
        ('coffees_api', '0002_alter_coffee_blend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='blend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coffees', to='blends_api.blend'),
        ),
    ]
