# Generated by Django 4.1.7 on 2023-03-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees_api', '0003_alter_coffee_blend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='blend',
            new_name='blend_id',
        ),
    ]
