# Generated by Django 4.1.7 on 2023-04-14 12:58

import coffees_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees_api', '0005_alter_coffee_calories_alter_coffee_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='calories',
            field=models.IntegerField(validators=[coffees_api.models.validate_positive, coffees_api.models.validate_calories]),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=50, validators=[coffees_api.models.validate_no_profanity]),
        ),
    ]
